version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/var/www:/var/www/html
      - ./nginx/logs:/var/log/nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - postgres
      - php-fpm
    networks:
      - app_network

  php-fpm:
    build:
      context: ./php-fpm
    image: php:8.0-fpm
    container_name: php-fpm
    volumes:
      - ./nginx/var/www:/var/www/html
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
